import XCTest

@testable import AgentTrackerCore

/// Locks in the exact on-disk output of install/uninstall so the provider-registry refactor can be
/// verified as pure code motion. These tests must survive the restructure unchanged.
final class HookInstallCharacterizationTests: XCTestCase {
  private var home: URL!
  private let helperPath = "/Applications/Agent Tracker.app/Contents/MacOS/agent-tracker"

  private static let executables: [Harness: String] = [
    .claude: "/usr/local/bin/claude",
    .codex: "/usr/local/bin/codex",
    .cursor: "/usr/local/bin/agent",
  ]

  override func setUpWithError() throws {
    home = FileManager.default.temporaryDirectory
      .appendingPathComponent("AgentTrackerHome-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
  }

  override func tearDownWithError() throws {
    try? FileManager.default.removeItem(at: home)
  }

  private func manager(resolving executables: [Harness: String] = executables)
    -> IntegrationManager
  {
    IntegrationManager(home: home, executableResolver: { executables[$0] })
  }

  func testInstallReportLines() throws {
    let report = try manager().install(helperPath: helperPath)
    XCTAssertEqual(
      report.lines,
      [
        "Installed managed zsh wrappers.",
        "Installed Claude lifecycle hooks.",
        "Installed Codex lifecycle hooks without changing config.toml or notify.",
        "Installed Cursor lifecycle hooks.",
        "Open a new shell or run: source ~/.zshrc",
      ])
    XCTAssertTrue(report.success)
  }

  func testInstallWarnsAboutMissingExecutables() throws {
    let report = try manager(resolving: [.claude: "/usr/local/bin/claude"])
      .install(helperPath: helperPath)
    XCTAssertEqual(
      Array(report.lines.prefix(2)),
      [
        "Warning: could not locate Codex; its wrapper was not installed.",
        "Warning: could not locate Cursor; its wrapper was not installed.",
      ])
  }

  func testUninstallReportLines() throws {
    _ = try manager().install(helperPath: helperPath)
    let report = try manager().uninstall()
    XCTAssertEqual(
      report.lines,
      [
        "Removed managed zsh wrappers.",
        "Removed Agent Tracker Claude hooks.",
        "Removed Agent Tracker Codex hooks.",
        "Removed Agent Tracker Cursor hooks.",
      ])
  }

  func testShellWrapperFileContents() throws {
    _ = try manager().install(helperPath: helperPath)
    let contents = try String(
      contentsOf: home.appendingPathComponent(".config/agent-tracker/shell.zsh"), encoding: .utf8)

    var expected =
      "# Generated by Agent Tracker. Use the app or `agent-tracker uninstall-integrations` to remove.\n"
    let quotedHelper = "'\(helperPath)'"
    for (harness, names) in [
      (Harness.claude, ["claude"]),
      (Harness.codex, ["codex"]),
      (Harness.cursor, ["agent", "cursor-agent"]),
    ] {
      let executable = Self.executables[harness]!
      for name in names {
        expected += """
          if (( ! $+aliases[\(name)] && ! $+functions[\(name)] )); then
            function \(name) { \(quotedHelper) wrap --harness \(harness.rawValue) -- '\(executable)' "$@"; }
          fi
          """ + "\n"
      }
    }
    XCTAssertEqual(contents, expected)

    let permissions =
      try FileManager.default.attributesOfItem(
        atPath: home.appendingPathComponent(".config/agent-tracker/shell.zsh").path
      )[.posixPermissions] as? NSNumber
    XCTAssertEqual(permissions?.intValue, 0o600)
  }

  func testZshrcBlockAppendedAndPreservesExistingContent() throws {
    let zshrc = home.appendingPathComponent(".zshrc")
    try Data("export PATH=/opt/bin:$PATH\n".utf8).write(to: zshrc)

    _ = try manager().install(helperPath: helperPath)

    let block = """
      # >>> agent-tracker >>>
      [[ -f "$HOME/.config/agent-tracker/shell.zsh" ]] && source "$HOME/.config/agent-tracker/shell.zsh"
      # <<< agent-tracker <<<
      """
    let contents = try String(contentsOf: zshrc, encoding: .utf8)
    XCTAssertEqual(contents, "export PATH=/opt/bin:$PATH\n\n" + block + "\n")

    _ = try manager().uninstall()
    let cleaned = try String(contentsOf: zshrc, encoding: .utf8)
    XCTAssertEqual(cleaned, "export PATH=/opt/bin:$PATH\n\n")
  }

  func testClaudeHookFileStructure() throws {
    _ = try manager().install(helperPath: helperPath)
    let root = try json(home.appendingPathComponent(".claude/settings.json"))
    let hooks = try XCTUnwrap(root["hooks"] as? [String: Any])

    let events = [
      "SessionStart", "UserPromptSubmit", "PermissionRequest", "Notification", "PreToolUse",
      "Stop", "SessionEnd",
    ]
    XCTAssertEqual(Set(hooks.keys), Set(events))
    for event in events {
      let entries = try XCTUnwrap(hooks[event] as? [[String: Any]], event)
      XCTAssertEqual(entries.count, 1, event)
      XCTAssertEqual(entries[0]["matcher"] as? String, "")
      let commands = try XCTUnwrap(entries[0]["hooks"] as? [[String: Any]], event)
      XCTAssertEqual(commands.count, 1)
      XCTAssertEqual(commands[0]["type"] as? String, "command")
      XCTAssertEqual(commands[0]["timeout"] as? Int, 5)
      XCTAssertEqual(
        commands[0]["command"] as? String,
        "'\(helperPath)' event --source agent-tracker --harness claude --event \(event)")
    }
  }

  func testCodexHookFileStructure() throws {
    _ = try manager().install(helperPath: helperPath)
    let root = try json(home.appendingPathComponent(".codex/hooks.json"))
    let hooks = try XCTUnwrap(root["hooks"] as? [String: Any])

    let events = [
      "SessionStart", "UserPromptSubmit", "PermissionRequest", "PreToolUse", "Stop", "SessionEnd",
    ]
    XCTAssertEqual(Set(hooks.keys), Set(events))
    for event in events {
      let entries = try XCTUnwrap(hooks[event] as? [[String: Any]], event)
      XCTAssertEqual(entries.count, 1, event)
      XCTAssertEqual(entries[0]["matcher"] as? String, "")
      let commands = try XCTUnwrap(entries[0]["hooks"] as? [[String: Any]], event)
      let expectedTimeout = event == "SessionEnd" ? 3 : 5
      XCTAssertEqual(commands[0]["timeout"] as? Int, expectedTimeout, event)
      XCTAssertEqual(
        commands[0]["command"] as? String,
        "'\(helperPath)' event --source agent-tracker --harness codex --event \(event)")
    }
  }

  func testCursorHookFileStructure() throws {
    _ = try manager().install(helperPath: helperPath)
    let root = try json(home.appendingPathComponent(".cursor/hooks.json"))
    XCTAssertEqual(root["version"] as? Int, 1)
    let hooks = try XCTUnwrap(root["hooks"] as? [String: Any])

    let events = [
      "sessionStart", "beforeSubmitPrompt", "preToolUse", "postToolUse", "postToolUseFailure",
      "beforeShellExecution", "afterShellExecution", "beforeMCPExecution", "afterMCPExecution",
      "afterFileEdit", "stop", "sessionEnd",
    ]
    XCTAssertEqual(Set(hooks.keys), Set(events))
    for event in events {
      let entries = try XCTUnwrap(hooks[event] as? [[String: Any]], event)
      XCTAssertEqual(entries.count, 1, event)
      // Cursor entries are flat commands, not nested matcher groups.
      XCTAssertNil(entries[0]["matcher"])
      XCTAssertNil(entries[0]["hooks"])
      XCTAssertEqual(entries[0]["timeout"] as? Int, 5)
      XCTAssertEqual(
        entries[0]["command"] as? String,
        "'\(helperPath)' event --source agent-tracker --harness cursor --event \(event)")
    }
  }

  func testCursorStatusLineContextBridgeStructure() throws {
    _ = try manager().install(helperPath: helperPath)
    let root = try json(home.appendingPathComponent(".cursor/cli-config.json"))
    let statusLine = try XCTUnwrap(root["statusLine"] as? [String: Any])
    XCTAssertEqual(statusLine["type"] as? String, "command")
    XCTAssertEqual(statusLine["padding"] as? Int, 0)
    XCTAssertEqual(
      statusLine["command"] as? String,
      "'\(helperPath)' cursor-context --source agent-tracker")

    _ = try manager().uninstall()
    let removed = try json(home.appendingPathComponent(".cursor/cli-config.json"))
    XCTAssertNil(removed["statusLine"])
  }

  func testCursorStatusLineInstallIsByteIdenticalOnRepair() throws {
    _ = try manager().install(helperPath: helperPath)
    let url = home.appendingPathComponent(".cursor/cli-config.json")
    let first = try Data(contentsOf: url)
    _ = try manager().install(helperPath: helperPath)
    XCTAssertEqual(try Data(contentsOf: url), first)
  }

  func testReinstallProducesByteIdenticalHookFiles() throws {
    _ = try manager().install(helperPath: helperPath)
    let paths = [".claude/settings.json", ".codex/hooks.json", ".cursor/hooks.json"]
    let first = try paths.map { try Data(contentsOf: home.appendingPathComponent($0)) }
    _ = try manager().install(helperPath: helperPath)
    let second = try paths.map { try Data(contentsOf: home.appendingPathComponent($0)) }
    XCTAssertEqual(first, second)
    for path in paths {
      let contents = try String(contentsOf: home.appendingPathComponent(path), encoding: .utf8)
      XCTAssertTrue(contents.hasSuffix("\n"), path)
      let permissions =
        try FileManager.default.attributesOfItem(
          atPath: home.appendingPathComponent(path).path)[.posixPermissions] as? NSNumber
      XCTAssertEqual(permissions?.intValue, 0o600, path)
    }
  }

  func testInstallBacksUpExistingConfiguration() throws {
    try FileManager.default.createDirectory(
      at: home.appendingPathComponent(".claude"), withIntermediateDirectories: true)
    try Data(#"{"model":"opus"}"#.utf8).write(
      to: home.appendingPathComponent(".claude/settings.json"))

    _ = try manager().install(helperPath: helperPath)

    let backups = try FileManager.default.contentsOfDirectory(
      at: home.appendingPathComponent(".claude"), includingPropertiesForKeys: nil
    ).filter { $0.lastPathComponent.contains("agent-tracker-backup") }
    XCTAssertEqual(backups.count, 1)
    XCTAssertTrue(backups[0].lastPathComponent.hasPrefix("settings.json.agent-tracker-backup-"))
  }

  private func json(_ url: URL) throws -> [String: Any] {
    try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any] ?? [:]
  }
}
