import Foundation

/// Owns the managed zsh wrapper file and the marked block in the user's `.zshrc` that sources it.
struct ShellIntegration {
  let home: URL
  let fileManager: FileManager

  private static let beginMarker = "# >>> agent-tracker >>>"
  private static let endMarker = "# <<< agent-tracker <<<"

  func installWrappers(helperPath: String, executables: [Harness: String]) throws {
    let directory = home.appendingPathComponent(".config/agent-tracker", isDirectory: true)
    try fileManager.createDirectory(
      at: directory,
      withIntermediateDirectories: true,
      attributes: [.posixPermissions: 0o700]
    )
    let wrapperFile = directory.appendingPathComponent("shell.zsh")
    var contents =
      "# Generated by Agent Tracker. Use the app or `agent-tracker uninstall-integrations` to remove.\n"
    for spec in ProviderRegistry.all {
      guard let executable = executables[spec.harness] else { continue }
      for name in spec.wrapperFunctionNames {
        contents += """
          if (( ! $+aliases[\(name)] && ! $+functions[\(name)] )); then
            function \(name) { \(ShellQuoting.quote(helperPath)) wrap --harness \(spec.harness.rawValue) -- \(ShellQuoting.quote(executable)) "$@"; }
          fi
          """ + "\n"
      }
    }
    try AtomicFileWriter.write(
      Data(contents.utf8), to: wrapperFile, permissions: 0o600, backup: true,
      fileManager: fileManager)

    let zshrc = home.appendingPathComponent(".zshrc")
    let current = (try? String(contentsOf: zshrc, encoding: .utf8)) ?? ""
    let block = """
      \(Self.beginMarker)
      [[ -f "$HOME/.config/agent-tracker/shell.zsh" ]] && source "$HOME/.config/agent-tracker/shell.zsh"
      \(Self.endMarker)
      """
    let cleaned = removeMarkedBlock(from: current)
      .trimmingCharacters(in: .newlines)
    let updated = cleaned.isEmpty ? block + "\n" : cleaned + "\n\n" + block + "\n"
    try AtomicFileWriter.write(
      Data(updated.utf8), to: zshrc, permissions: nil, backup: true, fileManager: fileManager)
  }

  func removeWrappers() throws {
    let zshrc = home.appendingPathComponent(".zshrc")
    if let current = try? String(contentsOf: zshrc, encoding: .utf8) {
      let updated = removeMarkedBlock(from: current)
      try AtomicFileWriter.write(
        Data(updated.utf8), to: zshrc, permissions: nil, backup: false, fileManager: fileManager)
    }
    let wrapperFile = home.appendingPathComponent(".config/agent-tracker/shell.zsh")
    if fileManager.fileExists(atPath: wrapperFile.path) {
      try fileManager.removeItem(at: wrapperFile)
    }
  }

  private func removeMarkedBlock(from source: String) -> String {
    guard let beginRange = source.range(of: Self.beginMarker),
      let endRange = source.range(
        of: Self.endMarker, range: beginRange.upperBound..<source.endIndex)
    else { return source }
    var result = source
    var removal = beginRange.lowerBound..<endRange.upperBound
    if removal.upperBound < result.endIndex, result[removal.upperBound] == "\n" {
      removal = removal.lowerBound..<result.index(after: removal.upperBound)
    }
    result.removeSubrange(removal)
    return result
  }
}
